name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          # A minimal fetch-depth of 2 is required
          # to automatically detect branch in @argos-ci/cli
          fetch-depth: 2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      # -----
      # Insert here your steps required to take screenshots of
      # your components or of your application.
      #
      # Find integrations on https://argos-ci.com/docs
      # -----

      - name: Upload screenshots to argos-ci.com
        continue-on-error: true
        run: npx @argos-ci/cli upload ./screenshots
